function[] = fPlot_xProfiles(c1xData, c2xData, c3xData,...
                 c1zData, c2zData, c3zData,...
                  xInt1, xInt2, xInt3,...
                   yInt1, yInt2, yInt3, dyInt1, dyInt2, dyInt3, write2disc)

mscrsz =   [0 0 3700 800];
fontS = 36;
MarkerS = 100;
MSdiv = 1/8;
yPos = 0.82; % y position of the textbox

black0=[0 0 0];
gray0=[.6 .6 .6];
gray1=[.58 .58 .58];
alphaVal = 0.2;
intpCol = [0.99 .99 .99];
intpColConf = [1 1 1];
%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','square','v','none','x'};
lStyles = {'none','-','--'};

figure1 = figure('Color',[1 1 1],'Position',[1 mscrsz(4) mscrsz(3) mscrsz(4)/1.4]);

%% SUBPLOT a) -- CASE 1.i
subplot1 = subplot(1,3,1,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0:20:120,...
    'YTick',0:5:20,...
    'Xdir','reverse',...
    'YAxisLocation','right',...
    'LineWidth', 2.5);
%    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
%    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
hold(subplot1,'all');
box(subplot1,'on');
grid(subplot1,'off');

xlim(subplot1,[0 120]);
ylim(subplot1,[0 20]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot1,'Layer','top','Clipping','on','ClippingStyle','rectangle');

% create plot of alpha
plot1(1) = plot(c1xData(1:2,1),c1zData(1:2,1)+100,...
    'Color',black0,...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS*MSdiv,...
    'DisplayName',' Hy - no \alpha');

% create plot of alpha
plot1(numel(plot1)+1) = plot(c1xData(1:2,2),c1zData(1:2,2)+100,...
    'Color',gray1,...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS*MSdiv,...
    'DisplayName',' Hy - no \beta');


% create legend here
lgnd = legend(subplot1,'show');
set(lgnd,'Location','SouthWest','LineWidth',1);

plot1(numel(plot1)+1) = scatter(c1xData(:,1),c1zData(:,1),MarkerS,...
    'MarkerEdgeColor',black0,...
    'MarkerEdgeAlpha',alphaVal,...
    'Marker',mStyles{1,1});

plot1(numel(plot1)+1) = scatter(c1xData(:,2),c1zData(:,2),MarkerS,...
    'MarkerEdgeColor',gray1,...
    'MarkerEdgeAlpha',alphaVal,...
    'Marker',mStyles{1,1});

% regression curve - confidence lower
plot1(numel(plot1)+1) = plot(xInt1,yInt1-dyInt1,...
    'Color',intpColConf,...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Lower');
plot1(numel(plot1)+1) = plot(xInt1,yInt1-dyInt1,...
    'Color',black0,...
    'LineWidth',3,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,4},...
    'DisplayName','Lower');
% regression curve 
plot1(numel(plot1)+1) = plot(xInt1,yInt1,...
    'Color',intpCol,...
    'LineWidth',4,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation curve');
% regression curve - confidence upper
plot1(numel(plot1)+1) = plot(xInt1,yInt1+dyInt1,...
    'Color',intpColConf,...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Upper');
plot1(numel(plot1)+1) = plot(xInt1,yInt1+dyInt1,...
    'Color',black0,...
    'LineWidth',3,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,4},...
    'DisplayName','Upper');

fMakeXgrid(20:20:100,[0,20],0.75);
fMakeYgrid([0,120],5:5:20,0.75);

% Create xlabel
xlabel('X_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
% ylabel('Z_* [-]',...
%     'FontSize',fontS,...
%     'FontName','Arial');

annotation(figure1,'textbox',...
        [0.31 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'a)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...    
        'LineStyle','none');
%% SUBPLOT b) -- CASE 2
subplot2 = subplot(1,3,2,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0:20:120,...
    'YTick',0:5:20,...
    'Xdir','reverse',...
    'YAxisLocation','right',...
    'LineWidth', 2.5);

hold(subplot2,'all');
box(subplot2,'on');
grid(subplot2,'off');

xlim(subplot2,[0 120]);
ylim(subplot2,[0 20]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot2,'Layer','top','Clipping','on','ClippingStyle','rectangle');

% create plot of alpha
plot2(1) = plot(c1xData(1:2,1),c2zData(1:2,1)+100,...
    'Color',black0,...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS*MSdiv,...
    'DisplayName',' Mec \alpha');

% create plot of alpha
plot2(numel(plot2)+1) = plot(c2xData(1:2,2),c2zData(1:2,2)+100,...
    'Color',gray1,...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS*MSdiv,...
    'DisplayName',' Mec \beta');


% create legend here
lgnd = legend(subplot2,'show');
set(lgnd,'Location','SouthWest','LineWidth',1);

plot2(numel(plot2)+1) = scatter(c2xData(:,1),c2zData(:,1),MarkerS,...
    'MarkerEdgeColor',black0,...
    'MarkerEdgeAlpha',alphaVal,...
    'Marker',mStyles{1,1});

plot2(numel(plot2)+1) = scatter(c2xData(:,2),c2zData(:,2),MarkerS,...
    'MarkerEdgeColor',gray1,...
    'MarkerEdgeAlpha',alphaVal,...
    'Marker',mStyles{1,1});

% regression curve - confidence lower
plot2(numel(plot2)+1) = plot(xInt2,yInt2-dyInt2,...
    'Color',intpColConf,...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Lower');
plot2(numel(plot2)+1) = plot(xInt2,yInt2-dyInt2,...
    'Color',black0,...
    'LineWidth',3,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,4},...
    'DisplayName','Lower');
% regression curve 
plot2(numel(plot2)+1) = plot(xInt2,yInt2,...
    'Color',intpCol,...
    'LineWidth',4,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation curve');
% regression curve - confidence upper
plot2(numel(plot2)+1) = plot(xInt2,yInt2+dyInt2,...
    'Color',intpColConf,...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Upper');
plot2(numel(plot2)+1) = plot(xInt2,yInt2+dyInt2,...
    'Color',black0,...
    'LineWidth',3,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,4},...
    'DisplayName','Upper');

fMakeXgrid(20:20:100,[0,20],0.75);
fMakeYgrid([0,120],5:5:20,0.75);

% Create xlabel
xlabel('X_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
% ylabel('Z_* [-]',...
%     'FontSize',fontS,...
%     'FontName','Arial');

annotation(figure1,'textbox',...
        [0.59 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'b)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');

%% SUBPLOT c) -- CASE 3
subplot3 = subplot(1,3,3,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTick',0:20:120,...
    'YTick',0:5:20,...
    'Xdir','reverse',...
    'YAxisLocation','right',...
    'LineWidth', 2.5);

hold(subplot3,'all');
box(subplot3,'on');
grid(subplot3,'off');

xlim(subplot3,[0 120]);
ylim(subplot3,[0 20]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot3,'Layer','top','Clipping','on','ClippingStyle','rectangle');

% create plot of alpha
plot3(1) = plot(c3xData(1:2,1),c3zData(1:2,1)+100,...
    'Color',black0,...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS*MSdiv,...
    'DisplayName',' HyMec.a_1 ');

% create plot of alpha
plot3(numel(plot3)+1) = plot(c3xData(1:2,3),c3zData(1:2,3)+100,...
    'Color',black0,...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS*MSdiv,...
    'DisplayName',' HyMec.a_2 ');

% create plot of alpha
plot3(numel(plot3)+1) = plot(c3xData(1:2,5),c3zData(1:2,5)+100,...
    'Color',black0,...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,5},'MarkerSize',MarkerS*MSdiv,...
    'DisplayName',' HyMec.a_3 ');

% create legend here
lgnd = legend(subplot3,'show');
set(lgnd,'Location','South','LineWidth',1);

plot3(numel(plot3)+1) = scatter(c3xData(:,1),c3zData(:,1),MarkerS,...
    'MarkerEdgeColor',black0,...
    'MarkerEdgeAlpha',alphaVal,...
    'Marker',mStyles{1,1});

plot3(numel(plot3)+1) = scatter(c3xData(:,2),c3zData(:,2),MarkerS,...
    'MarkerEdgeColor',gray1,...
    'MarkerEdgeAlpha',alphaVal,...
    'Marker',mStyles{1,1});

plot3(numel(plot3)+1) = scatter(c3xData(:,3),c3zData(:,3),MarkerS,...
    'MarkerEdgeColor',black0,...
    'MarkerEdgeAlpha',alphaVal,...
    'Marker',mStyles{1,3});

plot3(numel(plot3)+1) = scatter(c3xData(:,4),c3zData(:,4),MarkerS,...
    'MarkerEdgeColor',gray1,...
    'MarkerEdgeAlpha',alphaVal,...
    'Marker',mStyles{1,3});

plot3(numel(plot3)+1) = scatter(c3xData(:,5),c3zData(:,5),MarkerS,...
    'MarkerEdgeColor',black0,...
    'MarkerEdgeAlpha',alphaVal,...
    'Marker',mStyles{1,5});

plot3(numel(plot3)+1) = scatter(c3xData(:,6),c3zData(:,6),MarkerS,...
    'MarkerEdgeColor',gray1,...
    'MarkerEdgeAlpha',alphaVal,...
    'Marker',mStyles{1,5});

% regression curve - confidence lower
plot3(numel(plot3)+1) = plot(xInt3,yInt3-dyInt3,...
    'Color',intpColConf,...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Lower');
plot3(numel(plot3)+1) = plot(xInt3,yInt3-dyInt3,...
    'Color',black0,...
    'LineWidth',3,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,4},...
    'DisplayName','Lower');
% regression curve 
plot3(numel(plot3)+1) = plot(xInt3,yInt3,...
    'Color',intpCol,...
    'LineWidth',4,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation curve');
% regression curve - confidence upper
plot3(numel(plot3)+1) = plot(xInt3,yInt3+dyInt3,...
    'Color',intpColConf,...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Upper');
plot3(numel(plot3)+1) = plot(xInt3,yInt3+dyInt3,...
    'Color',black0,...
    'LineWidth',3,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,4},...
    'DisplayName','Upper');

fMakeXgrid(20:20:100,[0,20],0.75);
fMakeYgrid([0,120],5:5:20,0.75);

% Create xlabel
xlabel('X_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Z_* [-]',...
    'FontSize',fontS,...
    'FontName','Arial');

annotation(figure1,'textbox',...
        [0.8725 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'c)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');
%% Write Figure 2 disk
if write2disc
    cd('figures');
    export_fig xProfiles.png -png
    export_fig xProfiles.eps -eps
    export_fig xProfiles.jpg -jpg
    export_fig xProfiles.pdf -pdf
    cd ..
    disp('Figure (xProfiles) written to disc (figures folder).');
    close all;
end

